### ISSUE TITLE
未知问题。

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TW5-T-ONLINE#4]
@linonetwo 转让权限后，自己感觉是不是不太合适呀（捂脸），然后发现没有删除权限了。。。此仓库模仿太微中文和太记，是为了快速在github上部署tw的。

**Comment by Zacharia2** [comment]
如果不删除的话，希望可以把首页的链接删掉。

**Comment by linonetwo** [comment]
没啥问题，但是readme不大看得出这是做啥的

**Comment by Zacharia2** [comment]
![image](https://user-images.githubusercontent.com/32425955/212604624-a193beb4-c6b2-42ef-947a-717bd24d56ba.png)

希望改正此链接。或者去掉链接。

**Comment by linonetwo** [comment]
哦哦，帮你把权限加回来了

**Comment by Zacharia2** [comment]
三克油！
